# Numpy
## Two Dimensional Array
* Create a 2D Numpy Array
* Accessing different elements of a Numpy Array
* Basic Operations
# Create a 2D Array

In [2]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt


In [5]:
# create a list
a = [[11,12,13],[21,22,23],[31,32,33]]
print("list: ", a)
# cast list into numpy array
# every element is same type
A = np.array(a)
print("array: ",A)
print("numpy array dimensions: ",A.ndim)
print("numpy array shape: ", A.shape)
print("numpy array size: ", A.size)
# Acessing elements
print("element of second row and third column: ",A[1][2])
print("element of first row first column: ",A[0][0])
# Slicing
print(" element on the first row and first and second columns: ", A[0][0:2])
print("first two rows of 3rd column: ", A[0:2,2])


list:  [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
array:  [[11 12 13]
 [21 22 23]
 [31 32 33]]
numpy array dimensions:  2
numpy array shape:  (3, 3)
numpy array size:  9
element of second row and third column:  23
element of first row first column:  11
 element on the first row and first and second columns:  [11 12]
first two rows of 3rd column:  [13 23]


# Basic Operations
* Matrix addition
* multiplication by scalar
* dot product
* matrix multiplication
* Transposed matrix

In [8]:
# Create numpy arrays
X = np.array([[1,0],[0,1]])
Y = np.array([[2,1],[1,2]])
print("X",X)
print("Y",Y)

X [[1 0]
 [0 1]]
Y [[2 1]
 [1 2]]


In [9]:
Z= X+Y  # matrix addition
Z

array([[3, 1],
       [1, 3]])

In [10]:
Z= 2*X   # multiplication with scalar
Z

array([[2, 0],
       [0, 2]])

In [12]:
Z= np.dot(X,Y)   # dot product
Z

array([[2, 1],
       [1, 2]])

In [14]:
Z = X*Y   # multiply X with Y
Z

array([[2, 0],
       [0, 2]])

In [15]:
A = np.array([[0,1,1],[1,0,1]])
B = np.array([[1,1],[1,1],[-1,1]])
Z= np.dot(A,B)   # To multiply arrays
Z

array([[0, 2],
       [0, 2]])

In [16]:
np.sin(Z)  # calculate sine of Z

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [17]:
B.T    # transposed of matrix B

array([[ 1,  1, -1],
       [ 1,  1,  1]])

# Summary
In this lab we have learned about 2d array of numpy. we did matrix addition,multiplication.transposed,dot product.